### ISSUE TITLE
Remove duplicate code in server views

### ISSUE THREAD

**Issue by TimvdLippe** [bartdejonge1996/goto-fail-webserver#26]
Currently the elements in the views directoy contain a lot of duplicate code. Moreover, quite some elements are imported that are (probably) once used but not anymore. These should be cleaned up and integrated into a simpler structure to prevent code duplication.

**Comment by TimvdLippe** [comment]
Yeah, project is over yadada. Not gonna happen anymore :sob:

**Comment by martijnjanssen** [comment]
Unfortunately this project is indeed discontinue, feel free to leave feedback on our other projects though!
